### ISSUE TITLE
User & Account Model

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/blog#1]
**These are the required fields and the checkboxes mark the completed implementations**

### User/Account :  
- [x] Unique UserId(Auto Generated - UUID e.g 123e4567-e89b-12d3-a456-426614174000  or incremental Ids PK)    
- [x] Username(Combine First Name and Last Name ), 
- [x] Email Address(unique) 
- [x] Password, 
- [x] Phone Number(unique), 
- [x] Display Picture (url to image - assign them a default avatar) (Accounts)
- [x] Gender*(Keep it optional for now) 
- [x] Date Created, Date Updated 
- [x] Account Status  
- [x] Verification Code  
- [ ] Role_Id(FK)  #5 
- [x] About(Bio- short description of User)

**Comment by Fredrick-Waihenya** [comment]
I have tackled the verification code issue
