### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/blog#4]
### Reactions

- [ ] id(unique id)
- [ ] type -( up vote/down vote or like/dislike)- enumerated value
- [ ] user_id (FK) - links the reaction to a specific user who created it
- [ ] post_id
- [ ] comment_id
- [ ] date created,updated

**Comment by hellen-22** [comment]
I'll work on this.

**Comment by JimmyTron** [comment]
Ok
